<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/local/php_interface/class/DataHelper.php';

define("IBLOCK_ID_FORM_ORDER_SERVICE",8);
define("IBLOCK_ID_FORM_CLIENTS",6);
define("IBLOCK_ID_FORM_QUESTIONS",5);
define("CITIES_FROM",[
    "cn" => [
        "Shanghai, China",
        "Beijing(Peking), China",
        "Qingdao, China",
        "Guangzhou, China",
        "Foshan, China",
        "Fuzhou, China",
        "Ningbo, China",
        "Shenzhen, China",
        "Hong-Kong, China",
        "Changsha, China",
        "Hefei, China",
        "Xiamen, China",
        "Dalian, China",
        "Xingang, China",
        "Changzhou, China",
        "Chengdu, China",
        "Dongguan, China",
        "Huzhou, China",
        "Nanjing, China",
        "Nantong, China",
        "Shantou, China",
        "Suzhou, China",
        "Tianjin, China",
        "Wenzhou, China",
        "Wuxi, China",
        "Yiwu, China",
        "Zhongshan, China",
        "Busan, Korea",
        "Keelung, Taiwan",
        "HoChiMinh, Vietnam",
        "Yokohama, Japan",
        "Tokyo, Japan",
        "Osaka, Japan",
        "Кobe, Japan",
        "Nagoya, Japan",
        "Toyama, Japan",
        "Shimizu, Japan",
        "Singapore, Singapore",
        "Manila, Philippine",
        "Jakarta, Indonesia",
        "Mumbai, India",
        "Nhava Sheva, India",
        "Chennai, India",
        "Karachi, Pakistan",
        "Bangkok, Thailand",
        "Taizhou, China",
    ],
    "eu" => [
        "Milan, Italy",
        "Vilnius, Warszawa",
        "Prato, Italy"
    ]
]);
define("CITIES_TO",[
    "Москва",
    "Архангельск",
    "Астрахань",
    "Белгород",
    "Брянск",
    "Великие Луки",
    "Великий Новгород",
    "Владимир",
    "Волгоград",
    "Вологда",
    "Воронеж",
    "Екатеринбург",
    "Иваново",
    "Ижевск",
    "Казань",
    "Калуга",
    "Киров",
    "Клин",
    "Ковров",
    "Коломна",
    "Кострома",
    "Красногорск",
    "Краснодар",
    "Красноярск",
    "Кузнецк",
    "Курган",
    "Курск",
    "Липецк",
    "Магнитогорск",
    "Набережные Челны",
    "Нижнекамск",
    "Нижний Новгород",
    "Новосибирск",
    "Одинцово",
    "Омск",
    "Орел",
    "Оренбург",
    "Орск",
    "Пенза",
    "Пермь",
    "Петрозаводск",
    "Псков",
    "Ростов-на-Дону",
    "Рязань",
    "Самара",
    "Санкт-Петербург",
    "Саранск",
    "Саратов",
    "Смоленск",
    "Сочи",
    "Ставрополь",
    "Старый Оскол",
    "Сыктывкар",
    "Тамбов",
    "Тверь",
    "Тольятти",
    "Тула",
    "Тюмень",
    "Ульяновск",
    "Уфа",
    "Чебоксары",
    "Ярославль",
]);
//define("SPREAD_SHEET_ID","1MRW93djzAqh4NyoLPQ6ZKk5MHRATuH86dtMNXaCXqh0");
define("SPREAD_SHEET_ID","1UXF5-eXxOew6TcwTKkq3NePG6YkTVJfadOnjEpgOK1U");
define("KEY_FILE","ztm-test-1601831087518-2068998f3cb6.json");

?>